version: 2.1
orbs:
  cypress: cypress-io/cypress@3.1.2

workflows:
  use-my-orb:
    jobs:
      - setup-local-server:
          executor: local
      - cypress/run:
          requires:
            - setup-local-server
          cypress-command: npx cypress run --spec "cypress/e2e/first_daily.cy.js" --headless --config baseUrl=http://localhost:3000