version: 2.1
jobs:
  cypress-tests:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Cypress Tests
          command: CYPRESS_SPEC="cypress/e2e/PaymentCheck.cy.js" npx cypress run

workflows:
  version: 2
  cypress-workflow:
    jobs:
      - cypress-tests