version: 2.1
orbs:
  cypress: cypress-io/cypress@3.1.2

workflows:
  use-my-orb:
    jobs:
      - cypress/run:
          docker:
            - image: cypress/base:12
          steps:
            - checkout
            - run:
                name: Start Local Server
                command: npm start & sleep 10
            - cypress/run:
                requires:
                  - start-local-server
                cypress-command: npx cypress run --spec "cypress/e2e/first_daily.cy.js" --headless --config baseUrl=http://localhost:3000