name: Cassa

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: |
          npm install cypress --save-dev
          npm install -g http-server

      - name: Start Local Server
        run: http-server -p 8080 &

      - name: Wait for Server to Start
        run: |
          Start-Sleep -Seconds 5 # Adjust if needed
          $portOpen = $false
          while (-not $portOpen) {
            $connection = Test-NetConnection -ComputerName '127.0.0.1' -Port 8080
            $portOpen = $connection.TcpTestSucceeded
            Start-Sleep -Seconds 1
          }

      - name: Run Cypress tests
        run: npx cypress run --config baseUrl=http://127.0.0.1:8080 --spec "cypress/e2e/first_daily.cy.js"

      - name: Stop Local Server
        run: Stop-Process -Name "http-server" -Force
        
    env:
      CI: true