name: Run Cypress Tests

on: [push]

jobs:
  setup-and-run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Start Local Server
        run: |
          # Start your local server, for example:
          # npm start

          # Start ngrok to expose local server
          ngrok http 8080 > /dev/null &

          # Wait for ngrok to generate the public URL
          sleep 10
          echo "Public URL: $$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')"

      - name: Run Cypress Tests
        run: npx cypress run --spec "cypress/e2e/first_daily.cy.js" --headless --config baseUrl=https://your-ngrok-url

      - name: Stop Local Server
        run: |
          # Stop the local server
          # pkill -f "http-server"

          # Stop ngrok
          pkill -f "ngrok"
