name: Cassa

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          
      - name: Set screen resolution
        run: |
          sudo apt-get update
          sudo apt-get install xvfb -y
          export DISPLAY=:99
          Xvfb -screen 0 "${{ matrix.screen_resolution }}" &
          sleep 3 # Allow Xvfb to start    
          
      - name: Install Cypress
        run: npm install cypress --save-dev   

      - name: Run Cypress tests
        run: npm run test:cypress -- --spec "cypress/e2e/PaymentCheck.cy.js"
