name: Cassa

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Cypress
        run: npm install cypress --save-dev
      
      - name: Install server
        run: npm install -g http-server

      - name: Start Local Server
        run: npm run start-local-server # Replace with your start server command

      - name: Wait for Server to Start
        run: sleep 10 # Adjust as needed to give the server time to start

      - name: Run Cypress tests
        run: npx cypress run --spec "cypress/e2e/first_daily.cy.js --config baseUrl=http://10.107.2.79:8080"
        
    env:
      CI: true
